import Tkinter as tk


class DialogOrganizeViews(tk.Toplevel):
    def __init__(self, *args, **kargs):
        tk.Toplevel.__init__(self, *args, **kargs)
        self.title("Organize Views")
        v_2 = tk.IntVar()
        v_3 = tk.IntVar()
        v_4 = tk.IntVar()
        v_5 = tk.IntVar()
        v_6 = tk.IntVar()
        v_7 = tk.IntVar()
        v_8 = tk.IntVar()

        label_1 = tk.Label(self, text="Customize the views")
        label_2 = tk.Label(self, text="Project Navigation")
        label_3 = tk.Label(self, text="Dissector Building Area")
        label_4 = tk.Label(self, text="Palette")
        label_5 = tk.Label(self, text="Packet Stream Area")
        label_6 = tk.Label(self, text="Dissected Stream Area")
        label_7 = tk.Label(self, text="Raw Data Area")
        label_8 = tk.Label(self, text="Console Area")
        label_9 = tk.Label(self, text="Hide")
        label_10 = tk.Label(self, text="Show")
        button1 = tk.Button(self, text="Restore to Default")
        button2 = tk.Button(self, text="Confirm", command=self.destroy)
        button3 = tk.Button(self, text="Cancel", command=self.destroy)
        radio_button_hide_2 = tk.Radiobutton(self, variable= v_2 , value=0)
        radio_button_hide_3 = tk.Radiobutton(self, variable= v_3 , value=0)
        radio_button_hide_4 = tk.Radiobutton(self, variable= v_4 , value=0)
        radio_button_hide_5 = tk.Radiobutton(self, variable= v_5 , value=0)
        radio_button_hide_6 = tk.Radiobutton(self, variable= v_6 , value=0)
        radio_button_hide_7 = tk.Radiobutton(self, variable= v_7 , value=0)
        radio_button_hide_8 = tk.Radiobutton(self, variable= v_8 , value=0)
        radio_button_show_2 = tk.Radiobutton(self, variable= v_2 , value=1)
        radio_button_show_3 = tk.Radiobutton(self, variable= v_3 , value=1)
        radio_button_show_4 = tk.Radiobutton(self, variable= v_4 , value=1)
        radio_button_show_5 = tk.Radiobutton(self, variable= v_5 , value=1)
        radio_button_show_6 = tk.Radiobutton(self, variable= v_6 , value=1)
        radio_button_show_7 = tk.Radiobutton(self, variable= v_7 , value=1)
        radio_button_show_8 = tk.Radiobutton(self, variable= v_8 , value=1)
        label_1.grid(row=0, columnspan=3)
        label_9.grid(row=1, column=1)
        label_10.grid(row=1, column=2)
        label_2.grid(row=2)
        label_3.grid(row=3)
        label_4.grid(row=4)
        label_5.grid(row=5)
        label_6.grid(row=6)
        label_7.grid(row=7)
        label_8.grid(row=8)
        radio_button_hide_2.grid(row=2, column=1)
        radio_button_hide_3.grid(row=3, column=1)
        radio_button_hide_4.grid(row=4, column=1)
        radio_button_hide_5.grid(row=5, column=1)
        radio_button_hide_6.grid(row=6, column=1)
        radio_button_hide_7.grid(row=7, column=1)
        radio_button_hide_8.grid(row=8, column=1)
        radio_button_show_2.grid(row=2, column=2)
        radio_button_show_3.grid(row=3, column=2)
        radio_button_show_4.grid(row=4, column=2)
        radio_button_show_5.grid(row=5, column=2)
        radio_button_show_6.grid(row=6, column=2)
        radio_button_show_7.grid(row=7, column=2)
        radio_button_show_8.grid(row=8, column=2)
        button1.grid(row=9, column=1)
        button2.grid(row=9, column=2)
        button3.grid(row=9, column=3)